name: Pull Request Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  pr_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate PR
        run: |
          # Install dependencies
          npm ci

          # Run tests or perform linting
          npm lint

      - name: Merge to master
        if: github.event.pull_request.merged == true
        run: |
          # Merge the PR to the master branch
          git checkout master
          git merge ${{ github.event.pull_request.head.ref }}
