name: Pull Request Check


on:
#   push:
#       branches:
#         - 'ewa/*'
      
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  pr_check:
    runs-on: ubuntu-latest

    steps:
#       - name: git checkout
#         uses: actions/checkout@v3
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}

#       # https://github.com/marketplace/actions/github-pull-request-action
#       - name: create pull request
#         id: open-pr
#         uses: repo-sync/pull-request@v2
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN}}
#           destination_branch: ${{ github.event.repository.default_branch }}
#           pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
#           pr_body: "Automated Pull Request"
#           pr_reviewer: "mewwaa"
#           pr_assignee: "mewwaa"

#       # https://github.com/marketplace/actions/enable-pull-request-automerge
#       - name: enable automerge
#         if: steps.open-pr.outputs.pr_number != ''
#         uses: peter-evans/enable-pull-request-automerge@v2
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
#           merge-method: merge
      - name: Merge pull requests (automerge-action)
        uses: pascalgn/automerge-action@v0.15.6

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate PR
      
        run: |
          npm install
          npm run lint
          
            automerge:
                  - id: automerge
                    name: automerge
                    uses: "pascalgn/automerge-action@v0.15.6"
                    env:
                      GITHUB_TOKEN: "${{ secrets.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 }}"

#       - name: Merge to default branch
#         if: github.event.pull_request.merged == true
#         run: |
#           # Merge the PR to the default branch (e.g., main or master)
#           git checkout ${{ github.event.repository.default_branch }}
#           git merge ${{ github.event.pull_request.head.ref }}
